name: Test semantic-release-backmerge branch with semantic-release

on:
  workflow_dispatch:
    inputs:
      githubRepo:
        description: 'Repo of semantic-release-backmerge to use'
        default: 'github:saitho/semantic-release-backmerge'
        type: string
      repoBranch:
        description: 'Branch to use'
        required: true
        type: string
      semrelVersion:
        description: 'version of semantic-release to use'
        default: '^20.0.0'
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: "${{ secrets.COMMIT_KEY }}"
    - name: Update @saithodev/semantic-release-backmerge dependency
      run: echo "`jq '.dependencies["@saithodev/semantic-release-backmerge"]="${{ github.event.inputs.githubRepo }}#${{ github.event.inputs.repoBranch }}"' package.json`" > package.json
    - name: Update semantic-release dependency
      run: echo "`jq '.dependencies["semantic-release"]="${{ github.event.inputs.semrelVersion }}"' package.json`" > package.json
    - name: Read package.json
      run: cat package.json
    - name: Update timestamp to commit if no changes in JSON file
      run: echo $(date +%F_%T) > 'a.txt'
    - name: Set GitHub Actions as commit author
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - run: "git commit -am 'feat: ${{ github.event.inputs.githubRepo }}#${{ github.event.inputs.repoBranch }} with semantic-release ${{ github.event.inputs.semrelVersion }}' && git push"
