name: Test semantic-release-backmerge branch with semantic-release

on:
  workflow_dispatch:
    inputs:
      githubRepo:
        description: 'Repo of semantic-release-backmerge to use'
        default: 'github:saitho/semantic-release-backmerge'
        type: string
      repoBranch:
        description: 'Branch to use'
        required: true
        type: string
      semrelVersion:
        description: 'version of semantic-release to use'
        default: '^20.0.0'
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update @saithodev/semantic-release-backmerge dependency
      run: echo "`jq '.dependencies["@saithodev/semantic-release-backmerge"]="${{ github.event.inputs.githubRepo }}#${{ github.event.inputs.repoBranch }}"' package.json`" > package.json
    - name: Update semantic-release dependency
      run: echo "`jq '.dependencies["semantic-release"]="${{ github.event.inputs.semrelVersion }}"' package.json`" > package.json
    - name: Read package.json
      run: cat package.json
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        # scoped token with repo write access
        github_token: ${{ secrets.GH_ACCESS_TOKEN }}
