name: Test
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true
      - name: Compile semantic-release-backmerge sources
        run: (cd node_modules/@saithodev/semantic-release-backmerge && pnpm i && pnpm build)
      - run: pnpx semantic-release
        env:
          # Read access to metadata
          # Read and Write access to code
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}